export enum ParcelType {
  PALLET = 'pallet',
  BOX = 'box',
  ENVELOPE = 'envelope',
  EUROPALLET = 'europallet',
  PARCEL = 'parcel',
  OTHER = 'other',
  TEMP_CONTROLLED = 'temp_controlled',
  DOCUMENT = 'document',
  INSULATED_BOX = 'insulated_box',
  CARDBOARD_BOX = 'cardboard_box',
  PLASTIC_BOX = 'plastic_box',
  METAL_BOX = 'metal_box',
  WOODEN_BOX = 'wooden_box',
  OTHER_BOX = 'other_box',
  STYROFOAM_BOX = 'styrofoam_box',
  THERMOS = 'thermos',
  GLASS = 'glass',
  CYLINDER = 'cylinder',
  BARREL = 'barrel',
  BAG = 'bag',
  CRATE = 'crate',
  DRUM = 'drum',
  BOTTLE = 'bottle',
  CANISTER = 'canister',
  TANK = 'tank',
  GAS = 'gas',
  LIQUID = 'liquid',
  GAS_TANK = 'gas_tank',
}

export enum OperationStatus {
  PENDING = 'pending',
  CANCELED = 'canceled',
  DISPUTE = 'dispute',
  COMPLETED = 'completed',
}
